name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies & build
        run: |
          npm run setup
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          force_orphan: true
